os: linux
language: go
go: 1.7.1

install: make tools
before_script: make restore
script: make test-verbose
after_success: make package

deploy:
  provider: releases
  api_key:
    secure: gE+O8G3DK0jhYc7lIIz9wlRLSZTXau7WdWz3dQqG/DAPvkJbjcGAjA3WmW81KcEs4Ob0ODIdChSGJY5+px/w0aFTdAAP27NvoPRwute2VcLRevpjCglroqz3girj3KUVJmACtya4h/nJZ3Eo20/6/lTJTE6y6W9dVhbwx1DpKlM=
  file:
    - t2-linux.tgz
    - t2-darwin.tgz
  on:
    repo: albertrdixon/tmplnator
    tags: true
