os:
  - linux
  - osx
language: go
go: 1.4.1

install: go get github.com/tools/godep
script: make test-verbose
after_success: make package

deploy:
  provider: releases
  api_key:
    secure: gE+O8G3DK0jhYc7lIIz9wlRLSZTXau7WdWz3dQqG/DAPvkJbjcGAjA3WmW81KcEs4Ob0ODIdChSGJY5+px/w0aFTdAAP27NvoPRwute2VcLRevpjCglroqz3girj3KUVJmACtya4h/nJZ3Eo20/6/lTJTE6y6W9dVhbwx1DpKlM=
  file:
    - tnator-linux-amd64.tar.gz
    - tnator-darwin-amd64.tar.gz
  on:
    repo: albertrdixon/tmplnator
    tags: true

matrix:
  allow_failures:
    - os: osx
